name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Install Test Runner
        run: go install github.com/mfridman/tparse@latest
      - name: Test
        run: set -o pipefail && go test -json -v ./... | tparse -all

      - name: Lint
        run: go vet -v ./...
